### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/sablier-integration-template#11]
Since we will merge `v2-core` and `v2-periphery` into one repo called `lockup`, we should rename this afterward to `lockup-integration-template`

**Comment by smol-ninja** [comment]
How about calling it `sablier-integration-templates` and then include both `lockup` and `flow`?

```tree
src
├── lockup
│   └── templates goes here
└── flow
    └── templates goes here
```

**Comment by PaulRBerg** [comment]
I renamed it to `sablier-integration-template` now.

**Comment by smol-ninja** [comment]
Thoughts on deleting this repo? The [only template left](https://github.com/sablier-labs/sablier-integration-template/blob/main/src/StreamCreator.sol) in this repo is also [included in `examples` repo](https://github.com/sablier-labs/examples/blob/main/v2/core/LockupLinearStreamCreator.sol) already.

**Comment by andreivladbrg** [comment]
IIRC, the idea behind this repo is to simply fork it and start from scratch with some default things when integrating us (repo structure, NPM packages, etc.), so i think we should keep

**Comment by PaulRBerg** [comment]
Oh we should definitely keep this repo per what Andrei said. We have an entire guide in the docs that relies on this template.
